### ISSUE TITLE
Dependencies "StandardCplusplus" not existing ?!

### ISSUE THREAD

**Issue by atc1441** [atc1441/NETSGPClient#10]
While installing the Library from the Library manager it asks to also install also the dependencies which list is empty. 
But would normaly contain the StandardCplusplus which is not in my lists of librarys

![Dependencies](https://user-images.githubusercontent.com/1102694/158325566-9cdfd7e1-8f8c-421a-abb2-c26daad82dae.jpg)

Trying to install it ends up in an error, the "NETSGPClient" Library gets still installed.

![LogMSGS](https://user-images.githubusercontent.com/1102694/158325589-6a531260-7606-470d-8c0f-cee7b679a590.jpg)

The issue seems that the "StandardCplusplus" lib is not in the Arduino library list so will fail to install

Should we maybe remove the dependencie ?

**Comment by enwi** [comment]
I think we should remove it, because `StandardCplusplus` is not an "official" arduino library (bc it does not have the `library.properties` file), which causes this exception, because the library manager cannot find it.

**Comment by snelweg** [comment]
While installing the NETSGPClient I still get the missing StandardCplusplus error.

**Comment by enwi** [comment]
That is to be expected, because I haven't removed it from the `library.properties` file yet, hence the issue still being open
