### ISSUE TITLE
question: is it possible to use an nRF24L01

### ISSUE THREAD

**Issue by heiko1988** [atc1441/NETSGPClient#11]
Good day,

sorry im a noob, in this tech ;)

Can use an nRF24L01 in combination with an esp32 to query the data?

If it is possible, how do I have to adapt the script and connect the nRF24L01 to the esp32?

Thanks very much :)

**Comment by enwi** [comment]
Why would you want to use an nRF24L01?
Is this related to #6?

**Comment by heiko1988** [comment]
The problem is, the lc12s delivery time 1 months, and the nRF24L01 I have home.

When there is no way. Do I have to wait until the lc12 is there ;)

**Comment by enwi** [comment]
Are they compatible wireless protocol wise?

**Comment by enwi** [comment]
Theoretically it should be possible to make it work, thought the software might need to be refactored. I am thinking of the `Strategy`-pattern here

**Comment by heiko1988** [comment]
OK. Is it difficult to customize? I'm not that good at it. But would like to help

NRF24L01 has spi protocol 
Here a lot of information 
https://www.mikrocontroller.net/articles/NRF24L01_Tutorial

**Comment by enwi** [comment]
There is some work to be done, but I currently don't have that much time to do it. I have actually worked with the `NRF24L01+` a lot before and I would suggest to use [this library](https://github.com/nRF24/RF24) to control it.

**Comment by heiko1988** [comment]
Ok and the NRF24L01+ works with en esp32 oder esp8266 and the smart inverter sg600

When I order the NRF24L01+, come tomorrow :)

**Comment by atc1441** [comment]
Does the nRF24L01 even have a "Raw" radio RX mode? I reccon it was only compatible to Nordics proprietary one but that could be totally wrong.

At least the buffer of nRF24L01 is 32bytes max which could be a problem

**Comment by enwi** [comment]
> Are they compatible wireless protocol wise?

> Does the nRF24L01 even have a "Raw" radio RX mode? I reccon it was only compatible to Nordics proprietary one but that could be tottaly wrong.

That's why I asked 🤣

**Comment by heiko1988** [comment]
That's a good question, not familiar with the specs. Just have no experience with it. It will probably be best to wait for the ls12. Thank you very much for your information.

**Comment by atc1441** [comment]
Yeah would suggest on buying an LS12

**Comment by heiko1988** [comment]
Yes I have buy for 2 weeks, delivery time 4-6 weeks...

**Comment by atc1441** [comment]
Where are you from?

**Comment by heiko1988** [comment]
From Germany

**Comment by atc1441** [comment]
Nice can send you some. Please send a mail to heiko@43u.de

**Comment by heiko1988** [comment]
Perfect, have send you a mail
