### ISSUE TITLE
Solder an ESP directly to the inverter

### ISSUE THREAD

**Issue by majuss** [atc1441/NETSGPClient#14]
As far as I understood it, the wireless modules creating a raw bridge. So it would be possible to remove the rf module from the inverter and directly replace it with an ESP32? The only requirement would be, that the 3.3 V LDO is delivering enough current.

**Comment by majuss** [comment]
![Untitled342](https://user-images.githubusercontent.com/6533164/173204994-2f7be9d9-614c-4674-b258-6c9187ae9dfc.jpg)
So under the RF module is the LDO. A AMS1117 which can handle 1 A and is also used on the ESP32 WROOM board. So I think this shouldn't be a problem at all! I measured across the whole inverter board. The 3.3 V of this LDO is not used anywhere else.

**Comment by majuss** [comment]
So the ESP now is connected to the Inverter and I successfully uploaded the code. I'am not getting any valid status' :( Is the wireless module adding a layer of abstraction which I first of to remove from the code?

@enwi Could you please assist me removing the RF module code?

**Comment by enwi** [comment]
@majuss yes the RF module is adding a layer of abstraction to send the data over the air, but that is just the modulation of the transmitted signal. So once  another module receives the modulated data it demodulates it, so the module will spit out the same bytes you put into the sender. And in return this means removing the RF module from the inverter and talking to it directly should work, though you might need a level shifter if the inverter is running on a higher voltage than 3.3V and also you need to connect both RX to TX and TX to RX. The inverter won't send data on it's own, it needs to get a command to reply to first.

**Comment by enwi** [comment]
Also what makes you think that?
> The only requirement would be, that the 3.3 V LDO is delivering enough current.

**Comment by majuss** [comment]
Yeah you're right, maybe I need a level shifter, when the inverter is communicating with 5 V on tx and rx. But the rf module only survives 3.6 V, so it would be kinda surprising if it's running the serial interface on 5 V.

Could you give me hint what code I need to delete? I will dig into it tomorrow.

**Comment by enwi** [comment]
I don't think you need to modify the source code, in the examples you just need to remove or comment the following lines:
```c++
// Make sure the RF module is set to the correct settings
    if (!client.setDefaultRFSettings())
    {
        Serial.println("Could not set RF module to default settings");
    }
```

**Comment by majuss** [comment]
Thank you! I commented that out, but unfortunatley I still only get "Sending request now" and nothing else. I connected 26 V DC to the Inverter.

**Comment by majuss** [comment]
So I found out, that the RX and TX of the RF module is going to an PIC16F1936 which operates at 5 V with a 78M05 LDO. That suggests that the serial is indeed 5 V, but there is a 4.7 k resistor in series on the TX line. Which means the RF module is not recieving 5 but 3.3 V (at 0.35 mA). This resistor is missing on the RX line, which only has a pulldown of 10 k. So I won't need a level shifter in my opinion, since the RF module only runs at 3.3 V operating voltage, it has no way of sending 5 V signals to the PIC.

**Comment by enwi** [comment]
A series resistor can only limit the current, the voltage will only be affected slightly. A voltage divider can drop the voltage, but is also not ideal. Though I haven't looked into the schematic of the inverter and the code of the PIC is also closed source.

But I would say you would be fine connecting an ESP8266 directly as it is 5V tolerant, but I am not sure about an ESP32.

**Comment by majuss** [comment]
I think both are not 5 V tolerant :D

So I desoldered the RF module of one of my SG800MD's and connected it to my ESP32. Entered the inverter id and prog pin. The ESP is able to set the default values for the rf module and it is blinking every 2 seconds. But I'am still getting no data :/

<img width="1800" alt="Screenshot 2022-06-12 at 14 50 11" src="https://user-images.githubusercontent.com/6533164/173234065-0f908874-92c7-4998-9d59-af6c05109c5c.png">


The resistor should drop the voltage to 3.3 V as long as the current is not over 0.35 mA which seems reasonable for serial.
<img width="494" alt="Screenshot 2022-06-12 at 14 53 47" src="https://user-images.githubusercontent.com/6533164/173234206-acab60cd-f7a7-4988-a3e5-ff6bd3a11703.png">

**Comment by enwi** [comment]
> I think both are not 5 V tolerant :D

https://hackaday.com/2016/07/28/ask-hackaday-is-the-esp8266-5v-tolerant/

**Comment by enwi** [comment]
@majuss is the RF module blinking twice or only once every 2 seconds?

**Comment by majuss** [comment]
It only blinks once.

**Comment by enwi** [comment]
Okay that means that the inverter is not replying to the request. Then I would suggest to double check the inverter ID and if it is correctly set in the code

**Comment by majuss** [comment]
I already triple checked everything, but nothing has changed. I will receive my databox today and will see if that works.

**Comment by majuss** [comment]
Sooo big news, it's not working :D So I guess they accidentally swapped the stickers with the ID around... Is there any way to find out the ID? Maybe dump the flash of the PIC and search for '4500' in the dump?
The databox software is correctly registrating the inverter as SG800.

**Comment by enwi** [comment]
You can theoretically brute force it by making a loop through all possible identifiers and sending a request, if you get a reply you know the ID. Luckily you can reduce the number of IDs to search, because I think each model starts with a different constant ID. Though I don't know the starting ID for you model `SG800MD`, because I could not find a lot of information online. Your ID was `0x45002819` right? So you should search all IDs starting from `0x45000001` up to `0x4500FFFF`, which should not take that much time, maybe a couple of hours.

**Comment by majuss** [comment]
So just to clarify:
I connect `Set` to the GPIO pin specified in the arduino file and CS to gnd? For some reason I'am not able to "set RF module to default settings" :(

**Comment by majuss** [comment]
I found it, you mixed the TX and RX bin in your example. TX of the ESP has to go to the RX of the rf module.

**Comment by enwi** [comment]
> I found it, you mixed the TX and RX bin in your example. TX of the ESP has to go to the RX of the rf module.

TX and RX are not mixed in the example. It is commonly known that RX needs to be connected to TX and vice versa, but since the code is written for the ESP and not the RF module the TX/RX pin definitions refer to the ESP. But to make this more clear I could add a comment above these definitions 🙂

**Comment by majuss** [comment]
<img width="1028" alt="Screenshot 2022-06-17 at 19 25 06" src="https://user-images.githubusercontent.com/6533164/174348279-2325600a-a4aa-485d-b382-91895818c9f6.png">

It is defintely mixed up in your comment. PIN 17 of the ESP32 is TX. And you say, in the comment behind, that this Pin is going to the TX of the RF module!

**Comment by enwi** [comment]
Does it work now though?

**Comment by majuss** [comment]
Yes now it "works". I was too tired that day. I'am still not able to communicate with the inverter, but I guess it's because they never got a custom ID in production. The chinese support will send me a "universal ID" with that I should be able to talk to it... lets see how that will end.

**Comment by enwi** [comment]
> It is defintely mixed up in your comment

Oh you are right, I didn't know that it said RX/TX pin of the RF module, I will correct the comment for any future users.

> The chinese support will send me a "universal ID"

So you have been in touch with the manufacturer? Interesting that there is sth. like a universal ID. Would be interesting if the inverter replies to that

**Comment by majuss** [comment]
Soooo I have big news. I tried to brute force ID's starting from 45002800 but I had no luck. The chinese support got me the "universal ids" which didn't worked at all: 26002777 and 26002779. So this got me thinking and I started brute forcing from 26000000... And you wouldn't believe it. I found valid ids for my inverters: 45002818 has the ID 26002757 and 45002819 has 26002762.
I know compiled ESPhome and a custom sensor with your library which works flawless. In addition I replaced the RF module with the ESP32. Everything works and I know have the values directly in Home Assistant :)

**Comment by enwi** [comment]
Wow that's awesome 😊

But still weird that the IDs of your inverter don't match the inverter type afaik. But great that you could brute force the IDs. How long did it take to brute force btw?

**Comment by majuss** [comment]
Not that long. I think I tried 1 h with 45* and 1-2 h with 26*.

**Comment by WeareGermans** [comment]
Are you able to control the inverter, too?
As in changing the output power and switching the power on and off?

**Comment by majuss** [comment]
Sure thing it should work, why not?
But why would you want to change these parameters? It doesn't really make sense. Are you afraid because in germany there is only 600 W "allowed"?

**Comment by enwi** [comment]
Nonetheless I would say that this feature needs to be implemented in this library just to make it more so complete.

**Comment by WeareGermans** [comment]
Good question!
1. The design is flawed to not use the s.. word. My 700W inverter has 12.5A fuses soldered in line to each input. So 350W/24V= 14,6A. So 700W is not possible even in the optimal way of 2 strings of 350W in parallel.
2. I want to use it with a battery system and only switch it on at times where i am consuming more than it can deliver. (automated of cause) If i do not limit the power the fuse will (and already did ;-) ).

If you are already able to control it without the databox and software with only your ESP, that would help me very much! :-)

**Comment by WeareGermans** [comment]
Have you tested, whether you can control your inverter with the ESP32?
If not it would be great, if you try and report the outcome! :-)
Can you make any sense of the IDs that were given to you in comparison to the IDs that were/should have been on the label?
Is there possibly a pattern i could derive such an ID for my inverter using my official Label-ID?
Could it be that the inverter is only controllable with those "secret" IDs, if you do not own a databox?

**Comment by enwi** [comment]
@WeareGermans I for my part can tell you that my 2 inverters (both SG200MS) send back their status when using the ID's printed on them
