### ISSUE TITLE
Problem with Chipkit Max32

### ISSUE THREAD

**Issue by goliath51** [atc1441/NETSGPClient#18]
How do change your source with arduino 1.8 because I have this probleme:
AsyncNETSGPClient.h:48:5: error: 'set' in namespace 'std' does not name a type
     std::set<uint32_t> mDevices; /// All devices to poll

**Comment by enwi** [comment]
What architecture are you trying to compile for? `ESP8266`, `ESP32`, `AtMega328p`, ...

**Comment by goliath51** [comment]
chipKit max32

**Comment by enwi** [comment]
Does `max32` not support the standard c++ library?

**Comment by enwi** [comment]
Try installing [ArduinoSTL](https://github.com/mike-matera/ArduinoSTL) and include it before `NETSGPClient`

**Comment by goliath51** [comment]
it doesn't work because this is not avr architecture

**Comment by goliath51** [comment]
is it possible to use esp01s for this example (I think no because there is no two serial port, i know) or I can use serial -> wifi?

**Comment by enwi** [comment]
You could use an ESP01 with wireless serial (there are a few options, maybe take some inspiration from #13, which uses web serial)

**Comment by enwi** [comment]
Another option is to implement the `std::set` container yourself, but I would think that `ArduinoSTL` should work, because the c++ standard library should be architecture independent, have you tried it yet?

**Comment by goliath51** [comment]
error message:
```
ATTENTION : la bibliothèque ArduinoSTL prétend être exécutable sur la (ou les) architecture(s) avr, megaavr et peut être incompatible avec votre carte actuelle qui s'exécute sur pic32.
```

**Comment by enwi** [comment]
Isn't that just a warning?
```
WARNING: the ArduinoSTL library claims to be executable on the avr, megaavr architecture(s) and may be incompatible with your current board which runs on pic32.
```
In my opinion it would be odd if it does not work, but I also never used a chipKit max32 before

**Comment by goliath51** [comment]
I will try MQTT server with esp8266 #13 or directly solder on inverter #14

**Comment by enwi** [comment]
@goliath51 If you only have a single inverter then using the code from #13 and soldering the ESP directly to the inverter (#14) would be the best option

**Comment by enwi** [comment]
@goliath51 Any updates?
