### ISSUE TITLE
Problem Compiling Node MCU

### ISSUE THREAD

**Issue by damianburrin** [atc1441/NETSGPClient#19]
HI I can't get this to compile on a nodeMCU .  Getting an error about serial2 beiing used out of scope..

When i look at the ino file it does seem to try an call the object with serial2 but not declare this until the setup function.  Am i misunderstanding

Thanks
Damian

![image](https://user-images.githubusercontent.com/18092613/184550801-f6a118ed-6cec-4a38-b3ee-6d7d8a61a212.png)

**Comment by enwi** [comment]
@damianburrin The NodeMCU uses an ESP8266, which only has two Serial interfaces `Serial` and `Serial1`. In the example you will need to replace `Serial2` with `Serial`

**Comment by enwi** [comment]
I will update the example to make sure noone has this issue again

**Comment by damianburrin** [comment]
Brill

Thank you
