### ISSUE TITLE
Inverter Control

### ISSUE THREAD

**Issue by glennswest** [atc1441/NETSGPClient#2]
Can you turn off / turn on the inverter via rf message?

**Comment by atc1441** [comment]
Hey. 
Yes that is possible but currently not implemented in the lib.
Will be added in the future

**Comment by detobsen** [comment]
Hey, your work is so great. I cant wait to test your project in the future. 
Is it posible to get rid of the RF modul an daisy chain the UART between the inverters?

**Comment by enwi** [comment]
@detobsen I opened a new issue for you, because this one is not the right place to talk about your question

**Comment by detobsen** [comment]
Thanks

**Comment by enwi** [comment]
@glennswest Turning the inverter on/off (activating/deactivating it) has been added on the dev branch, if you want you can try it out
