### ISSUE TITLE
Pin Out Diagram

### ISSUE THREAD

**Issue by damianburrin** [atc1441/NETSGPClient#21]
Hi Aaron,

Is there any chance you could provide a pinout wiring diagram please.  I'm struggling to see which pins on the mcu connect to which on the rf module

It looks like 
3v3 to vcc
gnd to gnd
d8 to  rx
d7 to  tx
d6 to set

The code references Pin 16 and 17 for rx and tx and 4 got enable 

Just getting myself a little confused.

Any help appreciated

Thank you
Damian

**Comment by enwi** [comment]
The pin definitions are only for the ESP32. If you take a look at the examples on an ESP8266 D1 mini RX goes to TX and TX to RX and D2 to set:
https://github.com/atc1441/NETSGPClient/blob/5fc2908b7b5840f771b4629758138eb2d7d4f373/examples/AsyncDemo/AsyncDemo.ino#L13-L14

**Comment by damianburrin** [comment]
> The pin definitions are only for the ESP32. If you take a look at the examples on an ESP8266 D1 mini RX goes to TX and TX to RX and D2 to set:
> 
> https://github.com/atc1441/NETSGPClient/blob/5fc2908b7b5840f771b4629758138eb2d7d4f373/examples/AsyncDemo/AsyncDemo.ino#L13-L14

yeah i have esp32 and a nodemcu esp8266,  I'm trying the node but getting garbage output.  I'm clearly doing something wrong

![image](https://user-images.githubusercontent.com/18092613/185748400-77086a6e-3741-43af-82d7-507fe944767d.png)

**Comment by enwi** [comment]
On the ESP8266 you need to connect a USB to Serial Adapter to pin D4, because the default Serial is used for the communication with the LC12S module, that is why you are seeing garbage.

**Comment by damianburrin** [comment]
> On the ESP8266 you need to connect a USB to Serial Adapter to pin D4, because the default Serial is used for the communication with the LC12S module, that is why you are seeing garbage.

ok - i'll try to get it working with the ESP32 board i've got.  Pin positions are different but should be able to find a diagram to match up pin 16 and 17

**Comment by enwi** [comment]
Yeah using an ESP32 sure is easier for testing things out, the problem here is that you theoretically could output the log messages on the default Serial interface as well, but in reality the inverters don't like to receive more or less random data and will go into fault state.

**Comment by damianburrin** [comment]
Well getting closer

![image](https://user-images.githubusercontent.com/18092613/185749540-d2d67699-9379-4a28-a7e9-9785382e2e13.png)

**Comment by damianburrin** [comment]
Using Pin 4 to set pin but get not found error

![image](https://user-images.githubusercontent.com/18092613/185749850-229b1828-7db3-4ab2-8be6-2e4762a0d0fa.png)

**Comment by damianburrin** [comment]
It's really hard to tell from the video but Is the CS and gnd pin here joined so they both go to ground?

![image](https://user-images.githubusercontent.com/18092613/185750375-b0adf839-a75e-45e0-b5d3-78fefbedeff0.png)

**Comment by enwi** [comment]
Yes chip select needs to be grounded, it is active low.

**Comment by damianburrin** [comment]
> 

Cheers - i thought so, but still getting the same issue

**Comment by enwi** [comment]
Did you try swapping RX/TX?

**Comment by damianburrin** [comment]
Yeah – I’m just going to solder the connectors as they were just pinned in to make sure the connection is ok

**Comment by damianburrin** [comment]
Hmm no better

This is my board
![image](https://user-images.githubusercontent.com/18092613/185754112-17d700c6-df28-47d7-a869-84a305c0dac1.png)

and this is how i've set my id

![image](https://user-images.githubusercontent.com/18092613/185754195-cb2d441d-4e58-4bdf-9ecf-1ef404beff23.png)


Any thoughts would be great

**Comment by enwi** [comment]
I would check if nothing else is connected to the used pins and maybe use different ones if that is possible.

**Comment by damianburrin** [comment]
Thank you - you guys are the best.
Fully working and data being displayed on the built in screen of my board (Hiltec Wifi 32)

![20220822_140857](https://user-images.githubusercontent.com/18092613/185936476-d5085bfe-7104-4edf-a48d-3fb1b5cbe980.jpg)
