### ISSUE TITLE
Replacing LC12S with esp8266 for esp-link + mqtt

### ISSUE THREAD

**Issue by alexbenisch** [atc1441/NETSGPClient#22]
Hi,
I would like to get the inverter data via mqtt to node-red in Homeassistant.
Is the 2.4Ghz RF signal disturbing the wifi in the area?
Do you have any advice for me?

**Comment by enwi** [comment]
> Is the 2.4Ghz RF signal disturbing the wifi in the area?

AFAIK it does not disturb any WiFi networks

> Do you have any advice for me?

Please take a look at #13

**Comment by alexbenisch** [comment]
Thank you all! :+1:
