### ISSUE TITLE
Problem with SPIFFS_Test

### ISSUE THREAD

**Issue by GsDublin** [atc1441/NETSGPClient#23]
SPIFFS_Test stuck when I declare
```
NETSGPClient client(Serial2, PIN_LC12S_SET); /// NETSGPClient instance
```
at 
```
if (!SPIFFS.begin(FORMAT_SPIFFS_IF_FAILED)) {
```

function `esp_vfs_spiffs_register` will never finish.

This happens with ESP Core > 1.0.6

**Comment by GsDublin** [comment]
My workaround is to call the constructor within setup()

Declaration:
```AsyncNETSGPClient *client;```

setup():
```client = new AsyncNETSGPClient(Serial2, PIN_LC12S_SET); // Defaults to fetch status every 2 seconds```
```client->setStatusCallback(onInverterStatus);```

**Comment by enwi** [comment]
I can't see how this bug relates to this library, since we are not messing with `SPIFFS`

**Comment by enwi** [comment]
Also I cannot reproduce it on ESP Core > 1.06
