### ISSUE TITLE
Netsgpclient mqtt gateway advice needed

### ISSUE THREAD

**Issue by alexbenisch** [atc1441/NETSGPClient#28]
Enhancement Clarification
I would like to integrate the netsgpclient with a wifi client and pubsubclient to create a serial to mqtt bridge. The Programms themselves work but espclient wifi client and netsgpclient are too many clients. I hope you understand what I am trying to tell you. Can you tell me how it could work, please.
Thanks

**Comment by alexbenisch** [comment]
I need to have a look at C modules.

**Comment by enwi** [comment]
You can also take a look at #13
