### ISSUE TITLE
How to use library with only 1 serial port

### ISSUE THREAD

**Issue by 123gerald1** [atc1441/NETSGPClient#5]
Hello,
I have tried to compile the program, unfortunately I always get an error message.

Serial2' was not declared in this scope

What could be the reason for this?
Please for your help

**Comment by atc1441** [comment]
Hey. 

Sounds like you do not use ESP32 for it. 

It needs a device with 2 serial ports or a software serial instance

**Comment by 123gerald1** [comment]
Hello,
I would like to realize it either with a WEMOS D1 mini or with a Node MCU.
Is it possible with this?
Which board do you use?

**Comment by enwi** [comment]
Hey @123gerald1 you can use the library with the ESP8266 aka WEMOS D1 mini. So am I.

In the example code you just need to replace `Serial2` with `Serial1` and connect the RF module as follows:
- ESP 3V3 <-> VCC
- ESP TX <-> RX
- ESP RX <-> TX
- ESP D3 <-> SET
- ESP GND <-> CS
- ESP GND <-> GND

https://github.com/atc1441/NETSGPClient/blob/42189065c091018a775a8bf41f9c713e9931040a/examples/PollDemo/PollDemo.ino#L8
https://github.com/atc1441/NETSGPClient/blob/42189065c091018a775a8bf41f9c713e9931040a/examples/AsyncDemo/AsyncDemo.ino#L8
