### ISSUE TITLE
Hoymiles (HM-600) Support

### ISSUE THREAD

**Issue by Eule01x** [atc1441/NETSGPClient#6]
Hi,
I'm trying to read out the hoymiles HM-600 and got somehow stuck with my knowledge.

How did you manage to find out the meaning of received values and how to shift and calculate them?
How did you found out the correct value for the "command" 0xc0, 0xc1, 0xc3..? Magic Byte?

regards, Eule01x

**Comment by enwi** [comment]
The reverse engineering of the protocol was done by @atc1441, so maybe he can help here?

**Comment by enwi** [comment]
Also are you sure that the Hoymiles grid tie inverters use the same RF-Module?

**Comment by tbnobody** [comment]
Based on this: https://www.mikrocontroller.net/topic/525778#6931395 its a NRF 24LE1E

**Comment by enwi** [comment]
Well then it is not compatible atm
